-- Secret hiện 30 giây là quá ngắn với việc thật.
--
-- Cảnh dùng: đứng trước tủ rack, đọc một chuỗi kiểu `Qw3rty!@#$%^&*()_+` rồi gõ lại sang màn
-- hình khác. 30 giây là vừa đủ đọc xong thì hộp đóng, và người dùng bấm Xem lần nữa — mỗi lần
-- bấm là một dòng audit, nên nhật ký đầy những lần mở lặp chỉ vì đồng hồ chạy quá nhanh.
--
-- 60 giây: đủ đọc và gõ lại một lần, vẫn ngắn hơn nhiều so với thời gian một người rời bàn.
-- Grace step-up (`secret.stepup_grace_minutes = 10`) KHÔNG đổi — đó là câu hỏi khác: "bao lâu
-- thì phải gõ lại mã 6 số", và hộp hiện secret giờ đếm ngược cả hai số cạnh nhau (60s/600s).
--
-- AD-11: sửa giá trị ở đây, không sửa hằng số trong code.
UPDATE system_config SET value = '60' WHERE key = 'secret.reveal_seconds';
