-- ims:no-transaction
--
-- B-01 — CHỈ MỤC TÌM KIẾM CHO `device`. LƯỢT ĐẦU TIÊN DỰ ÁN DÙNG `ims:no-transaction` THẬT.
--
-- ===== VÌ SAO TÁCH KHỎI 0052 =====
--
-- `CREATE INDEX CONCURRENTLY` KHÔNG chạy được trong transaction, mà `migration-runner.ts`
-- bọc mọi file trong một transaction trừ khi thấy marker ở DÒNG ĐẦU. Marker phải là dòng
-- đầu tiên thật sự: `NO_TX_MARKER` khớp từ đầu CHUỖI, không có cờ `m`.
--
-- Và mỗi file no-transaction chỉ được chứa MỘT câu lệnh: nhiều câu trong một lượt simple
-- query vẫn bị Postgres bọc transaction ngầm, thế là marker mất tác dụng. Nên năm bảng =
-- năm file, 0053 tới 0057. Dài dòng, nhưng đó là cái giá của việc làm đúng.
--
-- ===== CONCURRENTLY CÓ MUA ĐƯỢC GÌ KHÔNG, KHI 0052 ĐÃ KHÓA BẢNG RỒI? =====
--
-- Có. 0052 thêm cột sinh nên có viết lại bảng và có giữ ACCESS EXCLUSIVE — nhưng đó là việc
-- tính vài trăm byte mỗi hàng, đo bằng giây. Dựng GIN trigram mới là phần đắt: 86 MB và
-- hàng phút ở cỡ một triệu dòng (§14 sổ rà soát). Để phần đắt ấy chạy CONCURRENTLY nghĩa là
-- người dùng chỉ mất vài giây lúc 0052 chạy, chứ không mất hàng phút.
--
-- ===== KHÔNG CÓ FILE `DROP INDEX CONCURRENTLY` ĐI TRƯỚC — VÀ ĐÂY LÀ LÝ DO =====
--
-- Chú thích trong `migration-runner.ts` khuyên đặt một file no-tx `DROP INDEX CONCURRENTLY
-- IF EXISTS` ngay trước mỗi file CIC. Đọc kỹ lại luồng thì nếp ấy KHÔNG mua thêm gì ở đây:
--
--   · CIC hỏng giữa chừng → chỉ mục INVALID, file NÀY chưa vào journal.
--   · Chạy lại: file DROP (nếu có) đã vào journal ở lượt trước nên bị BỎ QUA — nó không hề
--     dọn cho lượt thứ hai.
--   · `CREATE INDEX CONCURRENTLY IF NOT EXISTS` thấy chỉ mục INVALID thì coi là "đã có" và
--     không làm gì, rồi lưới an toàn của runner phát hiện `NOT indisvalid` và ĐỎ TO, kèm
--     đúng câu lệnh người trực cần gõ.
--
-- Tức là lưới của runner mới là thứ cứu, còn file DROP chỉ có tác dụng ở lượt chạy đầu — lượt
-- mà chưa có gì để dọn. Thêm năm file không làm gì là thêm năm chỗ để hiểu sai về sau.
--
-- Bài canh: `api/test/search-norm.spec.ts` — có ô hỏi thẳng `pg_index WHERE NOT indisvalid`.

CREATE INDEX CONCURRENTLY IF NOT EXISTS device_search_norm_trgm
  ON device USING gin (search_norm gin_trgm_ops);
