-- Q-15: quyền mở két gắn với PHIÊN đăng nhập đã gửi yêu cầu. Grant chỉ dùng được khi phiên đang
-- gọi trùng cột này và còn sống; phiên kết thúc là quyền hết, đăng nhập lại phải xin lại.
--
-- Giữ `sessions.id` (định danh nội bộ), không bao giờ giữ token hay bản băm token: cột này đọc
-- được trên đường nhật ký, còn token là chìa vào phiên.
--
-- Để trống được và KHÔNG có giá trị mặc định: thêm cột như vậy chỉ đổi catalog, không viết lại
-- bảng đang có dữ liệu. Phiếu cũ mang NULL, không khớp phiên nào, nên grant cấp trước luật này
-- hết hiệu lực — đúng ý Q-15.
--
-- Không khóa ngoại sang `sessions`: lượt dọn phiên cũ (`session-purge`) xóa hàng phiên, còn phiếu
-- là nhật ký FR-025 phải giữ nguyên.
ALTER TABLE approval ADD COLUMN requester_session_id uuid;
